export const COMMENTS = [
  'Всё отлично!',
  'В целом всё неплохо. Но не всё.',
  'Когда вы делаете фотографию, хорошо бы убирать палец из кадра. В конце концов это просто непрофессионально.',
  'Моя бабушка случайно чихнула с фотоаппаратом в руках и у неё получилась фотография лучше.',
  'Я поскользнулся на банановой кожуре и уронил фотоаппарат на кота и у меня получилась фотография лучше.',
  'Лица у людей на фотке перекошены, как будто их избивают. Как можно было поймать такой неудачный момент?!'
];

export const NAMES = [
  'Иван',
  'Александра',
  'Диана',
  'Анна',
  'Дарья',
  'Алексей',
  'Семён',
  'София',
  'Валерия',
  'Дмитрий',
  'Ярослав',
  'Ксения',
  'Алиса',
  'Матвей',
  'Елена',
  'Александр',
  'Василиса',
  'Андрей',
  'Элина',
  'Фёдор',
  'Мария',
  'Лев',
  'Иван',
  'Варвара',
  'Максим',
  'Тимофей',
  'Вероника',
  'Константин',
  'Злата',
  'Мирослава',
  'Ульяна',
  'Николай',
  'Роман',
  'Ясмина',
  'Дарья',
  'Майя',
  'Павел',
  'Мелания',
  'Оливия',
  'Елизавета',
  'Анна',
  'Артём',
  'Виктория',
  'Полина',
  'Малика',
  'Марк',
  'Даниил',
  'Алёна',
  'Илья',
  'Виктор',
  'Мира',
  'Екатерина',
  'Мирон',
  'Мадина',
  'Алиса',
  'Григорий',
  'Глеб',
  'Матвей',
  'Александр',
];

export const LOREM = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ex, vero quo ipsa omnis dolorem fuga quos error optio natus quam atque in delectus tenetur asperiores repellendus itaque quisquam vitae nemo? Tempora repellendus perspiciatis omnis quisquam voluptatibus earum, a amet tempore modi iure quam in neque at accusantium hic beatae adipisci quidem obcaecati velit! Expedita nihil nobis dignissimos repellat earum quibusdam sint reprehenderit, doloremque nostrum dolor itaque eius sed maxime eos tempore pariatur laborum similique totam ipsam minus nesciunt! Tempora odio ipsa repellendus alias. Unde inventore asperiores temporibus iure provident numquam, cumque dolor eos natus, voluptatem dolorum in corporis corrupti praesentium vel nesciunt? Quae necessitatibus dolor officiis, ea iusto perspiciatis possimus laboriosam minima. Labore, quia ratione! Aut minima, alias vel soluta voluptate corrupti, tempora molestias quisquam, velit esse blanditiis distinctio voluptatem voluptatibus optio. A ipsam voluptas non iusto nemo. Maiores saepe voluptatibus assumenda autem atque qui quod deserunt eum doloremque possimus, similique ad. Vero doloremque tempore ipsa nisi praesentium. Porro a sunt eum consequatur iure sit iusto illum? Iure quo et quisquam voluptates at optio incidunt animi, consequuntur est velit in tempore, qui ex eos ratione fugit libero. Illo, aut? Odio praesentium ad voluptate aspernatur optio quod ullam labore officia. Alias numquam dignissimos, quasi non eaque, praesentium ipsa asperiores blanditiis ad magnam excepturi placeat, incidunt sunt sed veritatis quod rem nesciunt eius minima aliquam atque nostrum iure. Amet distinctio vitae nulla quibusdam corrupti facere voluptate dolores voluptatem! Culpa, harum nam inventore illum officiis minima labore pariatur iste nisi quisquam doloribus cumque, quas esse asperiores corporis sapiente, veritatis distinctio qui ipsum nobis. Quos magni eum laudantium cupiditate harum veritatis? Dolor ipsam maxime explicabo soluta earum illum sequi reiciendis fugit accusantium molestiae minima quidem, aliquid vero modi dolores nobis officiis beatae optio ab, dicta ducimus quo consequuntur. Sed officia quae soluta aperiam eaque laboriosam, veritatis est, animi itaque ex voluptatum at vel voluptatibus facere nesciunt sequi nostrum ipsa nulla ratione autem? Distinctio blanditiis dolor maiores. Totam quaerat deserunt quasi, impedit eum ullam laboriosam porro molestiae natus omnis maiores cumque a cum voluptates officiis alias rerum modi numquam atque, tenetur id? Molestiae repellendus tempora hic assumenda quibusdam laboriosam fugit cupiditate voluptate, ut ad nisi, non dolor numquam! Pariatur nam eum aliquam architecto nihil, facilis soluta ut fugiat nisi, dicta corporis autem sequi dolorem obcaecati veritatis minima reprehenderit. Excepturi, ipsum sapiente quam fugiat assumenda nisi, blanditiis accusantium iusto obcaecati ex laboriosam ratione. Et dolorem facilis, reprehenderit dolores voluptatum nisi harum iste officia hic? Sunt quo placeat culpa alias eius magni, exercitationem dolor nesciunt molestias velit dicta blanditiis quidem! Error officiis voluptates repellat nobis fuga, voluptate beatae sunt temporibus dolores qui ea voluptatem adipisci, ratione, possimus dolor porro ex quo minus dicta earum! Nihil, sit minima molestias unde ratione labore enim neque earum numquam aliquam ab magni reiciendis dignissimos natus nam et vero repellendus quis incidunt ea nobis ullam optio? Sapiente doloremque soluta sed neque, mollitia, ipsum, quaerat nisi reprehenderit necessitatibus nostrum alias molestias inventore sit corrupti atque eligendi error? Similique, quaerat magni atque incidunt dignissimos facilis minima voluptates dolorum dolor voluptatibus cupiditate ad necessitatibus aspernatur non quasi vero officia odio possimus est obcaecati! Neque, ad inventore blanditiis itaque quis atque optio odio tenetur necessitatibus corrupti sed provident? Dolorem, suscipit repellendus! Quisquam illo laboriosam debitis architecto quod eum ad mollitia minus amet voluptatum aut pariatur, nihil ducimus ab voluptas quas, similique modi autem corrupti voluptate repellendus velit. Ducimus, natus? Culpa, illo fugit quidem excepturi eligendi consequuntur ipsa incidunt deserunt eveniet perspiciatis unde recusandae. Quibusdam aperiam temporibus incidunt similique, magni nam delectus corporis eaque? Debitis, vel quia quod harum atque, voluptatibus deleniti distinctio aspernatur rem alias provident magnam quos aliquam impedit eveniet officia doloribus facilis eligendi ipsum totam dicta placeat, numquam consequuntur repellat. Similique ab, sunt voluptas quo ea dicta ipsum reprehenderit vel sint illo quidem error esse ducimus nihil. Corrupti vitae inventore provident. Beatae recusandae unde ipsam quae earum ab voluptatum, magnam explicabo quibusdam architecto quis, quisquam nesciunt quam vitae quos reprehenderit eius natus facilis sunt molestias excepturi porro. Numquam, deleniti dignissimos mollitia exercitationem facere doloremque modi? Dolorum, atque saepe aspernatur eaque eum eius laudantium provident! Quibusdam, sit temporibus iusto culpa ipsa nulla incidunt quidem veniam at repudiandae dolor error vero iste facere aspernatur corrupti labore nisi tempore est. Perspiciatis harum dolore eaque repellendus maiores. Optio sunt recusandae molestias vel atque! Sapiente dolorem sit a? Quibusdam amet voluptate quis, reprehenderit nobis eveniet excepturi fugit dicta hic ea placeat laborum nam blanditiis, consequatur accusantium iste vero, tenetur ducimus dolorem sint tempora repudiandae numquam enim dolore? Sit fugit sequi facilis aspernatur aut numquam, totam nulla voluptatibus illo, ad, unde temporibus? Iusto nemo voluptates perspiciatis eligendi corrupti laudantium architecto a accusantium odio, suscipit beatae! Facere quasi tempora ipsum vitae quaerat! Earum, numquam maiores vel, neque dolore tenetur cum expedita quia molestiae ipsa a minima placeat nulla sint totam corporis impedit eos beatae. Rerum velit quam, itaque quasi repellendus architecto nostrum optio similique a laudantium provident cupiditate beatae quaerat recusandae deleniti explicabo possimus vitae ipsa, enim inventore perspiciatis? Unde consectetur autem porro voluptatum praesentium nobis, eos omnis saepe, nostrum cupiditate, minus quidem architecto eum. Magnam hic maiores soluta corrupti accusantium veritatis molestias omnis, architecto amet vero odio tenetur eos recusandae eligendi nostrum optio fuga aliquid fugit. Facilis fugiat necessitatibus, molestiae suscipit nesciunt quia repellendus qui beatae voluptate numquam sapiente facere ratione aperiam repudiandae asperiores quae autem aliquam voluptatem porro exercitationem minus veritatis. Alias ullam voluptas officia suscipit fugiat perferendis at veritatis animi voluptate beatae nemo tenetur molestiae numquam reprehenderit, unde cumque voluptatibus obcaecati quos maiores atque! Delectus pariatur nobis eos dolore nesciunt unde nisi laboriosam et ratione possimus facere corporis maxime, quasi cum culpa earum iure exercitationem iste, sequi non alias, eligendi dolorum eius? Quasi, architecto ad doloremque sed expedita qui odio ex aperiam molestiae est quaerat id amet praesentium quibusdam tempore, dolores laborum! Autem ipsa quaerat voluptates velit quibusdam vel quae enim, magni amet veniam quasi hic fugiat accusantium nihil commodi in? Aliquam, magnam pariatur alias animi nostrum earum eos dolorem, id, aut suscipit similique veritatis autem repellat!';
